workflows:
  flutter-ios-workflow:
    name: Flutter iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Check Flutter and Dart versions
        script: |
          flutter --version
          dart --version
          - flutter pub get
          - flutter build ios --release --no-codesign
          - flutter build ipa --release --no-codesign
      - name: Install dependencies
        script: |
          flutter pub get
          if [ $? -ne 0 ]; then
            echo "Failed to install dependencies"
            exit 1
          fi
      - name: Build iOS release
        script: flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
